version: '3.3'

services: 

    mirror:
        build: .
        command: /mirror.sh
        volumes:
            - "./mirror.sh:/mirror.sh:ro"
            - "./mirror:/downloads"

    server:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        restart: always
        command: [nginx-debug, '-g', 'daemon off;']
        volumes:
            - "./mirror:/downloads:ro"
        ports:
            - "8080:80"
